/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    Auth: {
      region: 'us-east-1',
      userPoolId: 'YOUR_USER_POOL_ID',
      userPoolWebClientId: 'YOUR_APP_CLIENT_ID',
      mandatorySignIn: true
  }
};


export default awsmobile;
